title: "1990 Commerce Batch"
description: "Classmates, photos, memories â€” Class of 1990 Commerce"
baseurl: ""
url: "https://frankdsouza.github.io/stphilomenabcom-1990/"
markdown: kramdown
theme: minima
collections:
  classmates:
    output: true

plugins:
  - jekyll-feed
